apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simple-flask-app
  labels:
    app: simple-flask-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app
        image: naveensi/simple-flask-app
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
kind: Service
apiVersion: v1
metadata:
  name: simple-flask-app
  annotations:
    service.beta.kubernetes.io/decc-load-balancer-https-backend-ports: "443"
    service.beta.kubernetes.io/decc-load-balancer-https-redirection-ports: "80:443"
spec:
  type: LoadBalancer
  selector:
    app: simple-flask-app
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5000
