# Need to map different pod ip:port with different service ports
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: NodePort
  selector:
    greeting: hello
    department: world
  ports:
  - name : app1
    protocol: TCP
    port: 80
    targetPort: 50000
  - name : app2
    protocol: TCP
    port: 81
    targetPort: 50001
