# If pods has been created with multiple open ports then service needs one port per open port of pod.
#
# From remote it can be accessed using that <ethernet_ip>:<node_port>. 
# node_port is a new port assigned to the service, which is visible in kubectl get service. 
# More details can be seen in kubectl describe service <svc-name>.
#
# Every service connects to the endpoints listed in its description. And, endpoints are the pod's ip:ports to connect to.
# Pods get different ip from a new virtual interface (tun10) which spawns up on every kubernetes node.
#
# Service (type NodePort) doesn't do load-balancing. It only does re-routing to the pods running on the same server, 
# which is queried or on which Cluster-ip is accessed from local.
#
# Read details of service re-routing in Chrome bookmarks.
#
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: NodePort
  selector:
    greeting: hello
    department: world
  ports:
  - name : app1
    protocol: TCP
    port: 80
    targetPort: 50000
  - name : app2
    protocol: TCP
    port: 81
    targetPort: 50001
